### ISSUE TITLE
Portal 2 currently crashes under FEX

### ISSUE THREAD

**Issue by Sonicadvance1** [FEX-Emu/FEX#3807] opened 2024-07-03 06:01 UTC
Seems to crash with a nullptr deference in their vscript.so library. Not sure what it is doing. Once at the title screen just click "Continue game" and seemingly once it gets done loading it'll crash before it goes in-game.

Trying to bisect this on the FEX side had me going back to FEX-2301 and still getting the crash. So this seems to have been a change on the Portal 2 side causing issues.

Doesn't seem to be running out of memory either, so it's a peculiar one. Might need to actually fix the gdbserver to debug this one.

Didn't try running it under Proton, which might be a viable workaround.

Dave the Diver and Peggle Deluxe breaking are likely related in some form.

**Comment by ektor5** [comment] 2024-08-28 23:07
Is this still valid? Seems now either a FEX commit or an app update fixed the issue. Tested on X1E80100, Debian Sid.

**Comment by ektor5** [comment] 2024-08-29 00:07
Talked too fast. It always crashes near the first elevator, after the first cube "puzzle". Might be something different than the original issue.

I tried debugging the crash with gdb:

```
Game.dll loaded for "Half-Life 2"
src/common/pipes.cpp (787) : bReceivedSomething
[New Thread 0xa6e63c80 (LWP 13838)]
[New Thread 0xccdf5c80 (LWP 13857)]
[New Thread 0x84a76c80 (LWP 13878)]
[Thread 0x84a76c80 (LWP 13878) exited]
[New Thread 0xc3fe3c80 (LWP 13899)]
[Thread 0xc3fe3c80 (LWP 13899) exited]
free(): invalid size

Thread 48 "FEXInterpreter" received signal SIGABRT, Aborted.
[Switching to Thread 0xccdf5c80 (LWP 13857)]
0x0000aaaaaad129f4 in unsigned long FEX::HLE::SyscallPassthrough3<131>(FEXCore::Core::CpuStateFrame*, unsigned long, unsigned long, unsigned long) ()
(gdb) disas 
Dump of assembler code for function _ZN3FEX3HLE19SyscallPassthrough3ILi131EEEmPN7FEXCore4Core13CpuStateFrameEmmm:
   0x0000aaaaaad129e0 <+0>:	mov	x0, x1
   0x0000aaaaaad129e4 <+4>:	mov	x1, x2
   0x0000aaaaaad129e8 <+8>:	mov	w8, #0x83                  	// #131
   0x0000aaaaaad129ec <+12>:	mov	x2, x3
   0x0000aaaaaad129f0 <+16>:	svc	#0x0
=> 0x0000aaaaaad129f4 <+20>:	ret
End of assembler dump.
(gdb) disas $pc,+32
Dump of assembler code from 0xaaaaaad129f4 to 0xaaaaaad12a14:
=> 0x0000aaaaaad129f4 <_ZN3FEX3HLE19SyscallPassthrough3ILi131EEEmPN7FEXCore4Core13CpuStateFrameEmmm+20>:	ret
   0x0000aaaaaad129f8 <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+0>:	mov	x0, x1
   0x0000aaaaaad129fc <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+4>:	mov	x1, x2
   0x0000aaaaaad12a00 <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+8>:	mov	x2, x3
   0x0000aaaaaad12a04 <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+12>:	mov	w8, #0xeb                  	// #235
   0x0000aaaaaad12a08 <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+16>:	mov	x3, x4
   0x0000aaaaaad12a0c <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+20>:	mov	x4, x5
   0x0000aaaaaad12a10 <_ZN3FEX3HLE19SyscallPassthrough6ILi235EEEmPN7FEXCore4Core13CpuStateFrameEmmmmmm+24>:	mov	x5, x6
End of assembler dump.
(gdb) backtrace 
#0  0x0000aaaaaad129f4 in unsigned long FEX::HLE::SyscallPassthrough3<131>(FEXCore::Core::CpuStateFrame*, unsigned long, unsigned long, unsigned long) ()
#1  0x0000000559f94d8c in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by CallumDev** [comment] 2024-09-10 09:26
Currently working fine @ 360ea53 on a Pi 5 with Ubuntu 24.04, running the GL renderer

**Comment by ektor5** [comment] 2024-09-10 10:09
Tested on cd4c224 and works as well. Working on DXVK on Proton as well. Portal 2 is not crashing anymore!
What could it have fixed it?

**Comment by jannau** [comment] 2024-10-04 00:32
The crash at the first elevator was reproducible on Asahi / M1 Ultra / Fedora 41 / FEX 2409 / OpenGL but seems to be fixed by #4101

**Comment by Sonicadvance1** [comment] 2024-10-04 00:33
No way. what.

**Comment by jannau** [comment] 2024-10-04 00:45
A', B, A, B tested with
A' -> FEX 2409 with "random" system setup
A -> FEX 2409
B -> FEX 2409 + #4101
system setup unchanged between A and B

**Comment by ektor5** [comment] 2024-10-04 14:40
I saw this already solved 3 weeks ago, regression + autofix? 
Portal 2 likes to break, it seems :D

**Comment by alyssarosenzweig** [comment] 2024-10-16 22:55
Optimistic this was the fmod thing. Portal 2 worked for me at least, closing. reopen if this comes back I guess

**Closed by alyssarosenzweig** 2024-10-16 22:55 UTC
Labels: Game related
