### ISSUE TITLE
[wine-i386]: [opengl can't detect hardware vendor]

### ISSUE THREAD

**Issue by baikaishiuc** [FEX-Emu/FEX#2192] opened 2022-12-05 02:08 UTC
**wine-i386 and winecheck*
Wine(https://www.winehq.org/)
winecheck

**Describe the bug**
I try to run x86 program in ubuntu-aarch64, so i use FEXLoader to load wine, then wine load x86 program wincheck.exe. But it seems cant find vendor
```
progwrapper$ FEXLoader -R Ubuntu_i386 ./wine-progwrapper/bin/wine ./winecheck.exe
[ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111 Connection refused
RootFS Position: /home/bogus/.fex-emu/RootFS/Ubuntu_i386 : ./wine-progwrapper/bin/wine
RootFS Position: /home/bogus/.fex-emu/RootFS/Ubuntu_i386 : /usr/local/share/progwrapper/wine-progwrapper/bin/wine-preloader
RootFS Position: /home/bogus/.fex-emu/RootFS/Ubuntu_i386 : /usr/local/share/progwrapper/wine-progwrapper/bin/wineserver
fixme:winediag:start_process Wine Staging 1.9.7 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
err:menubuilder:init_xdg error looking up the desktop directory
Checking OpenGL ...
radeon: Failed to get PCI ID, error number -1
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
OpenGL Vendor: VMware, Inc.
OpenGL Renderer: llvmpipe (LLVM 6.0, 128 bits)
OpenGL Direct Rendering: True
ERROR: found bad OpenGL Vendor: VMware, Inc.
ERROR: found bad OpenGL Renderer: llvmpipe
OpenGL: FAILURE
```
I read the source code, it seems failure in below part code, like this(https://github.com/wine-mirror/wine/blob/master/dlls/opengl32/tests/opengl.c#L1190), but is not the same:
```
	hWnd = CreateWindowExA(0, clsName, "OpenGL Test", WS_TILEDWINDOW, 0, 0, 100, 100, 0, 0, 0, 0);
	if (!hWnd)
		return false;

	hDC = GetDC(hWnd);
	if (!hDC)
		goto error;

	pixelformat = ChoosePixelFormat(hDC, &pfd);
	if (!pixelformat)
		goto error;

	if (!SetPixelFormat(hDC, pixelformat, &pfd))
		goto error;

	context = wglCreateContext(hDC);
	if (!context)
		goto error;

	if (!wglMakeCurrent(hDC, context))
		goto error;

	vendor		= (const char *)glGetString(GL_VENDOR);
	renderer	= (const char *)glGetString(GL_RENDERER);
	extensions	= (const char *)glGetString(GL_EXTENSIONS);

	if (extensions && strstr(extensions, "WINE_EXT_direct_rendering"))
		directRendering = true;

	printf("OpenGL Vendor: %s\n", vendor);
	printf("OpenGL Renderer: %s\n", renderer);
	printf("OpenGL Direct Rendering: %s\n",
	directRendering ? "True" : "False (or old/wrong wine version)");
``` 
glGetString(GL_VENDOR) cant get real vendor info, it's just return software implement. 

real vendor info :
![image](https://user-images.githubusercontent.com/618485/205528127-1a1fb4a1-d3ed-497d-957f-0942ff63b959.png)

Because I cant run winecheck, so I use some opengl test program do test, all is ok

1. FEXLoader ~/Downloads/ogl/glxinfo
2. WINEPREFIX="/home/bogus/.wine64/" ./wine ~/.wine64/drive_c/users/bogus/Temp/wct/opengl32_test.exe
3. FEXLoader  -k ~/.fex-emu/ThunkConfigs/thunks.json  -t /usr/lib/fex-emu/HostThunks/ -j /usr/share/fex-emu/GuestThunks -R ~/.fex-emu/RootFS/Ubuntu_22_04 --  ~/Downloads/ogl/glxinfo

And I think it is maybe FEX not implement some opengl32 compatibility interface, But how can I to verify my guess and to fix it? 

**To Reproduce**
FEXLoader -R Ubuntu_i386 ./wine-progwrapper/bin/wine ./winecheck.exe

**Expected behavior**
should like this:
![image](https://user-images.githubusercontent.com/618485/205528127-1a1fb4a1-d3ed-497d-957f-0942ff63b959.png)

**Screenshots and Video**

**System information:**
 - OS: Ubuntu 22.04.1 LTS
 - CPU/SoC: AMD
 - Video driver version:     Device: AMD OLAND (LLVM 13.0.1, DRM 2.50, 5.15.0-54-generic) (0x6611)
 - RootFS used: Ubuntu 16.04 (i386)
 - FEX version: commit c37fcf136ababf13b491ae8f1a878cc70f8d1c33 (FEXGetConfig build by myself, it seems is the latest version )
 - Thunks Enabled:  No (I don't know how to enable libgl32 thunk)

**Additional context**
 - Is this an x86 or x86-64 game: No
 - Does this reproduce on x86-64 host with FEX: NoTest
 - Does this reproduce on AArch64 with Radeon/Intel/Nvidia: yes
 - Is this a Vulkan game: No
 - 

**And I think it is maybe FEX not implement some opengl32 compatibility interface, But how can I to verify my guess and to fix it?**

**Comment by Sonicadvance1** [comment] 2022-12-05 02:58
A couple of things here are raising questions.

`[ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111 Connection refused`
This error is usually fatal but I guess since you're using an extracted rootfs, it happens to continue.

```
radeon: Failed to get PCI ID, error number -1
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
```
Looks like radeonsi/libdrm is trying to open to open the PCIe device but failing for some reason.
-1 is probably an artifact of FEX returning ioctl error numbers incorrectly. More likely is that it is failing with -EPERM or something.

`And I think it is maybe FEX not implement some opengl32 compatibility interface, But how can I to verify my guess and to fix it?`

We emulate at the syscall/ioctl level, so it is more likely any issue there.
I don't have a card this old so it's hard to reproduce here.

What kernel driver does this GPU use? For 32-bit we only support amdgpu, not radeon. This could be the issue you're encountering.

**Comment by baikaishiuc** [comment] 2022-12-05 03:14
> What kernel driver does this GPU use? For 32-bit we only support amdgpu, not radeon. This could be the issue you're encountering.

how to get current kernel driver the GPU use? glxinfo -B ?:
![image](https://user-images.githubusercontent.com/618485/205541590-fdc7e2a6-a3eb-46bd-aa36-f2e9acbf556c.png)

**Comment by Sonicadvance1** [comment] 2022-12-05 03:18
Try this:
```bash
lspci -vvv | grep -A20 "VGA compatible" | grep "VGA compatible\|Kernel driver in use"
```

eg:
```bash
$ lspci -vvv | grep -A20 "VGA compatible" | grep "VGA compatible\|Kernel driver in use"
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c0) (prog-if 00 [VGA controller])
        Kernel driver in use: amdgpu
```

**Comment by baikaishiuc** [comment] 2022-12-05 03:21
> Try this:
> 
> ```shell
> lspci -vvv | grep -A20 "VGA compatible" | grep "VGA compatible\|Kernel driver in use"
> ```

![image](https://user-images.githubusercontent.com/618485/205542311-28283d86-5078-457f-b3eb-30a545f30146.png)

woww, it seems a radeon driver, so If i want fix this problem , how could i support radeon 32 bit in my system?

**Comment by Sonicadvance1** [comment] 2022-12-05 03:35
You can either give this untested PR a try: https://github.com/FEX-Emu/FEX/pull/2193
Or on your end, you can switch your GPU's kernel driver from radeon to amdgpu if that is a suitable workaround.

**Comment by baikaishiuc** [comment] 2022-12-05 08:23
> You can either give this untested PR a try: #2193 Or on your end, you can switch your GPU's kernel driver from radeon to amdgpu if that is a suitable workaround.

I refer to amdgpu file structure and content:

![image](https://user-images.githubusercontent.com/618485/205587003-fc21bf7a-6437-4b7b-a926-d0881a5cb6f8.png)

and make a copy for radeon:
![image](https://user-images.githubusercontent.com/618485/205587143-4d796da0-6726-47d2-99b6-7b59828955fb.png)

In IoctlEmulation.cpp，I add follow content:
![image](https://user-images.githubusercontent.com/618485/205587403-3bd425f9-fca9-49a2-860e-2ba31e6ca2e4.png)
![image](https://user-images.githubusercontent.com/618485/205587468-34561777-df7e-4b86-8084-f093942456a1.png)

I rebuild it success. But at first I need to verify the original 64bit work flow correctly.  so I add some test code:

```
    uint32_t RADEON_Handler(int fd, uint32_t cmd, uint32_t args) {
      printf("radeon handler(%d, %d, 0x%08x). %s:%d\r\n", fd, cmd, args, __FILE__, __LINE__);

      exit(0);

   ...
   }
# run following command
~/source/FEX/build-Release-Thunk/Bin$ ./FEXLoader -- ~/Downloads/ogl/glxinfo -B 
```
the FEXLoader not exit success, and not print info. It seems this function not be invoked, I think I need do some configure, do you have suggestion to me?

**Comment by Sonicadvance1** [comment] 2022-12-05 08:37
64-bit doesn't use the same ioctl emulation, only 32-bit. Which is why it isn't hitting your test code.

**Comment by baikaishiuc** [comment] 2022-12-05 08:52
> 64-bit doesn't use the same ioctl emulation, only 32-bit. Which is why it isn't hitting your test code.

woow, I test a i386 glxinfo, it's work. Thank you.

Now i can go on

```
xianwei@xianwei:~/source/FEX/build-Release-Thunk/Bin$ ./FEXLoader -- ~/source/work/temp/glxinfo -B
[ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111 Connection refused
RootFS Position: /home/xianwei/.fex-emu/RootFS/Ubuntu_22_04_old : /home/xianwei/source/work/temp/glxinfo
name of display: :0
.[AssignDeviceTypeToFD] trace****** /home/xianwei/source/FEX/Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp:466 
.[AssignDeviceTypeToFD] trace****** /home/xianwei/source/FEX/Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp:466 
.[AssignDeviceTypeToFD] trace****** /home/xianwei/source/FEX/Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp:466 

```

**Comment by baikaishiuc** [comment] 2022-12-05 10:19
> 64-bit doesn't use the same ioctl emulation, only 32-bit. Which is why it isn't hitting your test code.

```
xianwei@xianwei:~/source/FEX/build-Release-Thunk/Bin$ ./FEXLoader  /usr/local/share/pipelight/wine-pipelight/bin/wine /usr/local/share/pipelight/winecheck.exe 
[ERROR] Couldn't connect to FEXServer socket 1000.FEXServer.Socket 111 Connection refused
RootFS Position: /home/xianwei/.fex-emu/RootFS/Ubuntu_i386 : /usr/local/share/pipelight/wine-pipelight/bin/wine
RootFS Position: /home/xianwei/.fex-emu/RootFS/Ubuntu_i386 : /usr/local/share/pipelight/wine-pipelight/bin/wine-preloader
RootFS Position: /home/xianwei/.fex-emu/RootFS/Ubuntu_i386 : /usr/local/share/pipelight/wine-pipelight/bin/wineserver
fixme:winediag:start_process Wine Staging 1.9.7 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
Checking OpenGL ...
OpenGL Vendor: X.Org
OpenGL Renderer: AMD OLAND (DRM 2.50.0 / 5.15.0, LLVM 6.0.0)
OpenGL Direct Rendering: True
OpenGL: PASSED

```

it worked, I post a PR in later

**Comment by Sonicadvance1** [comment] 2022-12-05 14:36
Fixed by https://github.com/FEX-Emu/FEX/pull/2193

**Closed by Sonicadvance1** 2022-12-05 14:36 UTC
Labels: Game related
