### ISSUE TITLE
Error opening steam 19772 Illegal instruction

### ISSUE THREAD

**Issue by Radiicall** [FEX-Emu/FEX#2567] opened 2023-03-27 11:48 UTC
```
$ FEXBash steam
erofsfuse 1.6
disk: /home/benja/.fex-emu/RootFS/Ubuntu_22_10.ero
offset: 0
mountpoint: /run/user/1000/.FEXMount19624-kmrhr3
dbglevel: 0
steam.sh[19631]: Running Steam on ubuntu 22.10 64-bit
steam.sh[19631]: STEAM_RUNTIME is enabled automatically
setup.sh[19711]: Steam runtime environment up-to-date!
steam.sh[19631]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2023-03-27 13:41:14] Startup - updater built Feb 14 2023 00:47:09
[2023-03-27 13:41:14] Startup - Steam Client launched with: '/home/benja/.local/share/Steam/ubuntu12_32/steam'
No minidump written, nothing to upload.
/home/benja/.local/share/Steam/steam.sh: line 798: 19772 Illegal instruction     (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```
Dumps are empty and i have no idea what i need to do to fix this

**Comment by Sonicadvance1** [comment] 2023-03-27 11:49
What is your FEX version? This can be seen with `FEXLoader --version`

**Comment by Radiicall** [comment] 2023-03-27 11:50
```
$ FEXLoader --version
FEX-Emu (FEX-2303-219-g9183cf1)
```
I rebuilt from source a couple of minutes before testing and posting this, have been getting this error for a few days

**Comment by Sonicadvance1** [comment] 2023-03-27 11:55
Might be a regression that I haven't tracked. This was tested fairly recently so it's a little surprising. There was a bug that could have broken steam in a older release but was fixed.
Before launching steam setting a couple of environment variables might give more information.
`FEX_SILENTLOG=0 FEX_OUTPUTLOG=stderr FEXBash steam` might give more information.

**Comment by Radiicall** [comment] 2023-03-27 12:55
```
$ FEX_SILENTLOG=0 FEX_OUTPUTLOG=stderr FEXBash steam
erofsfuse 1.6
disk: /home/benja/.fex-emu/RootFS/Ubuntu_22_10.ero
offset: 0
mountpoint: /run/user/1000/.FEXMount21250-iw5CSW
dbglevel: 0
steam.sh[21258]: Running Steam on ubuntu 22.10 64-bit
steam.sh[21258]: STEAM_RUNTIME is enabled automatically
setup.sh[21368]: Steam runtime environment up-to-date!
steam.sh[21258]: Can't find 'steam-runtime-check-requirements', continuing anyway
[2023-03-27 14:48:30] Startup - updater built Feb 14 2023 00:47:09
[2023-03-27 14:48:30] Startup - Steam Client launched with: '/home/benja/.local/share/Steam/ubuntu12_32/steam'
[ERROR] Unknown DRM device: 'apple'
[ERROR] Unknown DRM device: 'apple'
[Info] clone: Unsuported flags w/o CLONE_THREAD (Shared Resources), 800600
No minidump written, nothing to upload.
/home/benja/.local/share/Steam/steam.sh: line 798: 21451 Illegal instruction     (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
```
Okay thanks for the debugging flags, there's something wrong with my GPU driver then (probably). I'm currently on a 4k kernel with the GPU driver patched to run on 4k kernels. I need to figure out what I'm doing differently from Asahi Lina.

**Comment by Sonicadvance1** [comment] 2023-03-27 12:57
You don't have the patch to FEX that is necessary to bring up the asahi GPU. Also there isn't an asahi video driver in the rootfs currently. Tricky when none of the asahi drm stuff is upstream to the kernel or mesa. Not upstream because its not ready on their end.

**Comment by Radiicall** [comment] 2023-03-27 12:59
I have an x86 version of the driver in `/usr/lib/i386-linux-gnu/` and an x86_64 version of the driver in `/usr/lib/x86_64-linux-gnu`. Can you send me the branch/repo with the patch so i can test it out? Before i added the drivers it complained about loading mesa but it doesnt do that anymore.

**Comment by Sonicadvance1** [comment] 2023-03-27 13:00
I don't believe they pushed their FEX patches anywhere for this

**Comment by Radiicall** [comment] 2023-03-27 13:00
hmm that sucks, guess ill have to wait with this then...

**Comment by Sonicadvance1** [comment] 2023-06-28 17:18
Fix for the initial SIGILL from steam has been fixed, will be in the FEX-2307 release.

**Closed by Sonicadvance1** 2023-06-28 17:18 UTC
